# 2장 파이썬 프로그래밍

## 2.1 연산과 자료형태

In [1]:
x = 9
print(x)
print(type(x))
print(id(x))
x = 9.0
print(x); print(type(x)); print(id(x)); # ‘;’ 는 여러 명령어를 한 줄에 기록

9
<class 'int'>
140727864932384
9.0
<class 'float'>
2897592296144


In [2]:
x = x + 5
print(x+3); print(x-3)
print(x*3); print(x/3)
print(x%3); print(x//3)
print(x**2)

17.0
11.0
42.0
4.666666666666667
2.0
4.0
196.0


In [3]:
y = 10; y += 1
print(x,y)
temp = x
x = y
y = temp
print(x,y)
x, y = y, x
print(x,y)

14.0 11
11 14.0
14.0 11


In [4]:
print(x > y); print(x < y)
print(x <= y); print(x >= y)
print(x == y); print(x != y)
print(x is y); print(x is not y)

True
False
False
True
False
True
False
True


In [5]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [6]:
x = True
x
type(x)

True

bool

In [7]:
print(True & False)
print(True | False)
print(True and False)
print(True or False)

False
True
False
True


In [8]:
True + 1
True*10
True + True
False + 1
False*10

2

10

2

1

0

In [9]:
x = '파이썬 프로그래밍 언어는 쉽고 간결합니다.'
x
type(x)

'파이썬 프로그래밍 언어는 쉽고 간결합니다.'

str

In [10]:
x.replace('썬', '선')
x.replace('파이썬', '파송송')
'언어' in x
x + x
len(x)
x.find('썬')
x[0]
x[-1]
x[-2]

'파이선 프로그래밍 언어는 쉽고 간결합니다.'

'파송송 프로그래밍 언어는 쉽고 간결합니다.'

True

'파이썬 프로그래밍 언어는 쉽고 간결합니다.파이썬 프로그래밍 언어는 쉽고 간결합니다.'

23

2

'파'

'.'

'다'

In [11]:
type(9), type(1.5e5), type('파이썬')
print('정수: {0:d}, 문자 : {1:.3f}, 실수 : {2:s}'.format(9, 5e5, '파이썬'))
print('수자이지만 문자로 출력 {0!s} 실수로 출력 {1:.2f}'.format(1.5e5, 1.5e5))

(int, float, str)

정수: 9, 문자 : 500000.000, 실수 : 파이썬
수자이지만 문자로 출력 150000.0 실수로 출력 150000.00


In [12]:
name ='파이썬'; language = '영어'; sex ='남성'
f'Hi, I am {name}, I like to use {language}. I am {sex}. Nice to meet you.'

'Hi, I am 파이썬, I like to use 영어. I am 남성. Nice to meet you.'

In [13]:
'Hi, I am %s, '%name
'I like to use %s.'%language

'Hi, I am 파이썬, '

'I like to use 영어.'

In [14]:
x = 9; y = 10.24
print(f'{x}와 {y} 그리고 더하면 {x+y}')

9와 10.24 그리고 더하면 19.240000000000002


In [15]:
x = [] 
x = [9, 9.0, '파이썬', True] 
x
type(x)

[9, 9.0, '파이썬', True]

list

In [16]:
len(x)
x[2]
x[1:3]
8 in x

4

'파이썬'

[9.0, '파이썬']

False

In [17]:
x.append('대한민국')
x
x = [9,5,3,7,1,11]
sorted(x)
sorted(x, reverse=True)

[9, 9.0, '파이썬', True, '대한민국']

[1, 3, 5, 7, 9, 11]

[11, 9, 7, 5, 3, 1]

In [18]:
x = {}  # x = dict()
x = {'a':1, 'b':3, 'c':5, 'd':7}
x
type(x)

{'a': 1, 'b': 3, 'c': 5, 'd': 7}

dict

In [19]:
len(x)
x['a']
x['e']= 9
x
x.items(); x.keys()
x.values()

4

1

{'a': 1, 'b': 3, 'c': 5, 'd': 7, 'e': 9}

dict_items([('a', 1), ('b', 3), ('c', 5), ('d', 7), ('e', 9)])

dict_keys(['a', 'b', 'c', 'd', 'e'])

dict_values([1, 3, 5, 7, 9])

In [20]:
dict([(value, key) for (key, value) in x.items()])
x.get('c')

{1: 'a', 3: 'b', 5: 'c', 7: 'd', 9: 'e'}

5

In [21]:
sorted(x.items(), key=lambda kv: kv[0], reverse=True)

[('e', 9), ('d', 7), ('c', 5), ('b', 3), ('a', 1)]

In [22]:
is_opensource = True
if is_opensource  :
    print('파이썬은 무료 공개 소스다.')
else:
    print('파이썬은 무료 공개 소스가 아니다.')

파이썬은 무료 공개 소스다.


In [23]:
A = {}; B = {'파이썬':10, '자바':5}
if A :
    print("The Object A is not empty")
else :
    print("The Object A is empty.")
    
if '파이썬' in B:
    print('B에 파이썬이 있다.')
if '파이썬' not in A:
    print('A에 파이썬이 없다.')

The Object A is empty.
B에 파이썬이 있다.
A에 파이썬이 없다.


In [193]:
for i in range(0,3):
    print(i)

0
1
2


In [122]:
mylist =[]               
for x in [1,2,3,4,5] :  
    if x >=2:           
        mylist.append(x) 
mylist

[x for x in [1,2,3,4,5] if x >=2] 

[2, 3, 4, 5]

[2, 3, 4, 5]

In [123]:
[i for i in range(0,10)]
[i for i in reversed([i for i in range(1,11)])]
sum([i for i in reversed([i for i in range(1,11)])])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

55

## 2.2 Numpy와 Pandas

In [124]:
import numpy as np

In [125]:
list(range(10))
np.array(range(0,10))
np.arange(10)
np.arange(0,10,2)
list(np.arange(0,10,2))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 2, 4, 6, 8])

[0, 2, 4, 6, 8]

In [126]:
np.arange(10)
np.arange(0, 20, 2)
np.hstack([np.arange(10), np.arange(0, 20, 2)])
np.vstack([np.arange(10), np.arange(0, 20, 2)])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  0,  2,  4,  6,  8, 10, 12,
       14, 16, 18])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]])

In [127]:
%time s = sum([i for i in range(1,99999)])

%time s = np.arange(99999).sum()

Wall time: 4.99 ms
Wall time: 0 ns


In [128]:
np.random.seed(1357)
m = np.random.randint(1,100,12)
m

m.max()
m.min()
m.sum()
m.mean()
m.std()

array([52, 71, 72, 80, 72, 53, 71, 46, 68, 59, 55, 19])

80

19

718

59.833333333333336

15.836841716565697

In [129]:
m.argmin() 
m.argmax()
m.argsort()
np.argsort(-m)

11

3

array([11,  7,  0,  5, 10,  9,  8,  1,  6,  2,  4,  3], dtype=int64)

array([ 3,  2,  4,  1,  6,  8,  9, 10,  5,  0,  7, 11], dtype=int64)

In [130]:
m.shape
m.reshape(-1,1).shape

(12,)

(12, 1)

In [131]:
m
m.shape
mr = m.reshape(3,4)
mr

array([52, 71, 72, 80, 72, 53, 71, 46, 68, 59, 55, 19])

(12,)

array([[52, 71, 72, 80],
       [72, 53, 71, 46],
       [68, 59, 55, 19]])

In [132]:
mr[2][3]
mr[0:2] 
mr[:, [1,2]]
mr[:, 0:3]
mr[:2, 2:]

19

array([[52, 71, 72, 80],
       [72, 53, 71, 46]])

array([[71, 72],
       [53, 71],
       [59, 55]])

array([[52, 71, 72],
       [72, 53, 71],
       [68, 59, 55]])

array([[72, 80],
       [71, 46]])

In [133]:
import pandas as pd
data = m.reshape((3,4))
pd.DataFrame(data)

0   1   2   3
0  52  71  72  80
1  72  53  71  46
2  68  59  55  19

In [134]:
index = range(1,4)
columns = ['A','B','C','D']
df = pd.DataFrame(data, index = index, columns = columns)
df

A   B   C   D
1  52  71  72  80
2  72  53  71  46
3  68  59  55  19

In [135]:
df.loc[2]
df.iloc[1]
df.loc[2, 'B']
df.iloc[1, 1]

A    72
B    53
C    71
D    46
Name: 2, dtype: int32

A    72
B    53
C    71
D    46
Name: 2, dtype: int32

53

53

In [136]:
df['A']
type(df['A'])
df[['A','B']]
type(df[['A','B']])
df[['A','B']].loc[2]

1    52
2    72
3    68
Name: A, dtype: int32

pandas.core.series.Series

A   B
1  52  71
2  72  53
3  68  59

pandas.core.frame.DataFrame

A    72
B    53
Name: 2, dtype: int32

In [137]:
df[1:]
df[-1:]

A   B   C   D
2  72  53  71  46
3  68  59  55  19

A   B   C   D
3  68  59  55  19

In [138]:
df['A']
df.A

1    52
2    72
3    68
Name: A, dtype: int32

1    52
2    72
3    68
Name: A, dtype: int32

In [139]:
df>=60
df[df>=60]
np.array(df>=60)*1 # (df>=60).values*1
pd.DataFrame(np.array(df>=60)*1, index = index, columns = columns)

A      B      C      D
1  False   True   True   True
2   True  False   True  False
3   True  False  False  False

A     B     C     D
1   NaN  71.0  72.0  80.0
2  72.0   NaN  71.0   NaN
3  68.0   NaN   NaN   NaN

array([[0, 1, 1, 1],
       [1, 0, 1, 0],
       [1, 0, 0, 0]])

A  B  C  D
1  0  1  1  1
2  1  0  1  0
3  1  0  0  0

In [140]:
df[df['C']>60]
df[(df['B']>50)&(df['C']<70)]

A   B   C   D
1  52  71  72  80
2  72  53  71  46

A   B   C   D
3  68  59  55  19

In [141]:
df = df[df>60].copy()
df['E'] = ['owl', 'fox', 'owl']
df
df.isnull().sum()
df.nunique()
df.dtypes

A     B     C     D    E
1   NaN  71.0  72.0  80.0  owl
2  72.0   NaN  71.0   NaN  fox
3  68.0   NaN   NaN   NaN  owl

A    1
B    2
C    1
D    2
E    0
dtype: int64

A    2
B    1
C    2
D    1
E    2
dtype: int64

A    float64
B    float64
C    float64
D    float64
E     object
dtype: object

In [142]:
type(df.isnull().sum()); df.isnull().sum().shape
type(df.nunique()); df.nunique().shape
type(df.dtypes); df.dtypes.shape

pandas.core.series.Series

(5,)

pandas.core.series.Series

(5,)

pandas.core.series.Series

(5,)

In [143]:
df.fillna(0)
df.fillna(0, inplace = True)  # df = df.fillna(0)
df

A     B     C     D    E
1   0.0  71.0  72.0  80.0  owl
2  72.0   0.0  71.0   0.0  fox
3  68.0   0.0   0.0   0.0  owl

A     B     C     D    E
1   0.0  71.0  72.0  80.0  owl
2  72.0   0.0  71.0   0.0  fox
3  68.0   0.0   0.0   0.0  owl

In [144]:
df = pd.DataFrame(mr, index = [i for i in 'abc'], columns = ['A','B','C','D'])
df
df.drop('c')
df.drop(['a', 'c'])

A   B   C   D
a  52  71  72  80
b  72  53  71  46
c  68  59  55  19

A   B   C   D
a  52  71  72  80
b  72  53  71  46

A   B   C   D
b  72  53  71  46

In [145]:
df.drop('C', axis=1)
df.drop(['A', 'C'], axis=1)

A   B   D
a  52  71  80
b  72  53  46
c  68  59  19

B   D
a  71  80
b  53  46
c  59  19

In [146]:
df.loc['d'] = df.loc['b']
df
df.duplicated()
df[~df.duplicated()]

A   B   C   D
a  52  71  72  80
b  72  53  71  46
c  68  59  55  19
d  72  53  71  46

a    False
b    False
c    False
d     True
dtype: bool

A   B   C   D
a  52  71  72  80
b  72  53  71  46
c  68  59  55  19

In [147]:
print(type('hello'))
print(type(sum([1,2,3])))

<class 'str'>
<class 'int'>


In [148]:
def summary(df) :
    tf = pd.DataFrame({'데이터형태(dtypes)' : df.dtypes,
                       '결측치 수(null)' : df.isnull().sum(),
                       '고유값 수(nunique)' : df.nunique()})
    return tf

print(type(summary(df)))
summary(df)

<class 'pandas.core.frame.DataFrame'>


데이터형태(dtypes)  결측치 수(null)  고유값 수(nunique)
A         int32            0               3
B         int32            0               3
C         int32            0               3
D         int32            0               3

In [149]:
def test_var_args(f_arg, *argv):
    print("first normal arg:", f_arg)
    for arg in argv:
        print("another arg through *argv:", arg)

test_var_args('sanggoo', 'python', 'eggs', 'apple')

first normal arg: sanggoo
another arg through *argv: python
another arg through *argv: eggs
another arg through *argv: apple


In [150]:
def greet_me(**kwargs):
    for key, value in kwargs.items():
        print("{0} = {1}".format(key, value))
        
greet_me(name="sanggoo", fruit ="apple")

name = sanggoo
fruit = apple


In [151]:
def add(x, y, z=1) :
    return (x + y + z)
add(10, 20, z=50)

80

In [152]:
def display(add, *arg, **kwargs) :
    print(arg)
    print(kwargs)
    print(add)
    
    return add(*arg, **kwargs)

In [153]:
display(add, 10, 20, z=50)

(10, 20)
{'z': 50}
<function add at 0x000001BE1BD4B048>


80

In [154]:
print(type(1.0))
print(type('hello'))

<class 'float'>
<class 'str'>


In [155]:
class Member:
    def name():
        print('모른다')
        
    def age():
        print('알거없다')

In [156]:
m = Member()
print(type(m))

<class '__main__.Member'>


In [157]:
m.name()

TypeError: name() takes 0 positional arguments but 1 was given

In [158]:
class Member:
    def name(a):
        print('모른다')
        
    def age():
        print('알거없다')

In [159]:
m = Member()
m.name()
m.grade()

모른다


AttributeError: 'Member' object has no attribute 'grade'

In [ ]:
class Member:
    def __init__(self, name, age):
        self.name = name
        self.age = age    
        
    def get_name(self):
        return self.name      
    
    def get_age(self):
        return self.age
    
    def set_age(self, age):
        self.age = age

In [160]:
m = Member('홍길동', 23)
m.get_name()
m.get_age()

TypeError: Member() takes no arguments

In [161]:
m.set_age(33)
m.name
m.age
m.get_age()

AttributeError: 'Member' object has no attribute 'set_age'

In [162]:
class Student:
    def __init__(self, name, age, grade):
        self.name = name
        self.age = age
        self.grade = grade
        
    def get_grade(self):
        return self.grade 

    def show(self):
        print(f'내 이름은 {self.name}, {self.age}살 이야.') 

class Course:
    def __init__(self, name, max_students) :
        self.name = name
        self.max_students = max_students
        self.students = []
        self.is_active = False
        
    def add_student(self, student):
        print(student)
        if len(self.students) < self.max_students:
            self.students.append(student)
            return '수강신청 완료'
        return '최대인원 초과로 수강신청 불가'
    
    def get_average_grade(self):
        value = 0
        for student in self.students:
            value += student.get_grade()
        return value/len(self.students)

In [163]:
s1 = Student('Tim', 19, 95)
s2 = Student('Bill', 19, 75)
s3 = Student('Jill', 19, 65)

In [164]:
course =Course('Science', 2)
course
course.add_student(s1)
course.add_student(s2)

'수강신청 완료'

'수강신청 완료'

In [165]:
print(type(course.students))
course.students
print(course.students[0])
print(course.students[0].name)

<class 'list'>


[<__main__.Student at 0x1be1bd4aac8>, <__main__.Student at 0x1be1bd4a948>]

Tim


In [166]:
course.add_student(s3)
print(course.get_average_grade())

'최대인원 초과로 수강신청 불가'

85.0


In [167]:
class Female(Student):
    def speak(self):
        print('어머나 어머나')
        
class Male(Student):
    def speak(self):
        print('아이쿠 아이쿠')

In [168]:
f = Female('Eve', 16, 75) 
f.show()
m = Male('Adam', 18, 65)
m.show
m.show()

내 이름은 Eve, 16살 이야.


<bound method Student.show of <__main__.Male object at 0x000001BE1BD09648>>

내 이름은 Adam, 18살 이야.


In [169]:
f.speak()
m.speak()

어머나 어머나
아이쿠 아이쿠


In [1]:
txt = '    필 땐 장미꽃처럼, 흩날릴 땐 벚꽃처럼, 질 땐 나팔꽃처럼'
txt2 = '아름다운 그 순간처럼, 어짜피 이것 밖에 난 못해'
txt3 = '너를 사랑하는 것 밖엔 못해'
type(txt)

str

In [2]:
txt.split() 
type(txt.split())
' '.join(txt.split(' '))

'    필 땐 장미꽃처럼, 흩날릴 땐 벚꽃처럼, 질 땐 나팔꽃처럼'

In [3]:
txt.strip()

'필 땐 장미꽃처럼, 흩날릴 땐 벚꽃처럼, 질 땐 나팔꽃처럼'

In [4]:
txt[0:10]
txt.find('장미')

8

In [5]:
txt.replace('장미', '해바라기')

'    필 땐 해바라기꽃처럼, 흩날릴 땐 벚꽃처럼, 질 땐 나팔꽃처럼'

In [8]:
doc = pd.Series([txt, txt2, txt3], dtype="string")
doc = doc.to_frame()
doc

0
0      필 땐 장미꽃처럼, 흩날릴 땐 벚꽃처럼, 질 땐 나팔꽃처럼
1           아름다운 그 순간처럼, 어짜피 이것 밖에 난 못해
2                       너를 사랑하는 것 밖엔 못해

In [176]:
doc[0].str.contains('장미')

0     True
1    False
2    False
Name: 0, dtype: boolean

In [177]:
for choice in ['장미', '벚꽃', '사랑'] :
    doc[choice] = doc[0].str.contains(choice).fillna(0).astype(int)
doc

0  장미  벚꽃  사랑
0      필 땐 장미꽃처럼, 흩날릴 땐 벚꽃처럼, 질 땐 나팔꽃처럼   1   1   0
1           아름다운 그 순간처럼, 어짜피 이것 밖에 난 못해   0   0   0
2                       너를 사랑하는 것 밖엔 못해   0   0   1

In [13]:
doc1= ['사과', '오렌지', '수박']
doc2= ['토마토', '수박', '토마토']
doc3= ['사과', '토마토', '사과',]
df=pd.DataFrame(list(zip(doc1, doc2, doc3)))
df

0    1    2
0   사과  토마토   사과
1  오렌지   수박  토마토
2   수박  토마토   사과

In [179]:
choices = set(df[0].values) | (set(df[1].values)) | (set(df[2].values))
choices

{'사과', '수박', '오렌지', '토마토'}

In [180]:
df['all'] = df.apply(','.join, axis=1)
df

0    1    2         all
0   사과  토마토   사과   사과,토마토,사과
1  오렌지   수박  토마토  오렌지,수박,토마토
2   수박  토마토   사과   수박,토마토,사과

In [181]:
for choice in choices :
    df[choice] = df['all'].str.contains(choice)*1
df

0    1    2         all  오렌지  토마토  사과  수박
0   사과  토마토   사과   사과,토마토,사과    0    1   1   0
1  오렌지   수박  토마토  오렌지,수박,토마토    1    1   0   1
2   수박  토마토   사과   수박,토마토,사과    0    1   1   1

In [9]:
txt = '%    ?필 땐 /장미꽃:처럼!, 흩날릴\t 땐 !벚꽃처럼, $질 땐 나팔꽃처럼'
txt2 = '!아름다운 ?그 <순간처럼>, !어짜피 %이것 밖에 난 못해'
txt3 = '너를 %%사랑하는 것% 밖엔 못해'
doc = pd.Series([txt, txt2, txt3], dtype="string").to_frame()
doc

0
0  %    ?필 땐 /장미꽃:처럼!, 흩날릴	 땐 !벚꽃처럼, $질 땐 나팔꽃처럼
1             !아름다운 ?그 <순간처럼>, !어짜피 %이것 밖에 난 못해
2                            너를 %%사랑하는 것% 밖엔 못해

In [10]:
import re
p = re.compile('처럼')
print(p.findall(txt))

['처럼', '처럼', '처럼']


In [11]:
regex = ['[%]', '[?]', '[!]', '[/]', '[$]', '[>]', '[<]', '[:]', '\t']
def RegularClear(regex) :
    for pattern in regex :
        p = re.compile(pattern)
        doc[0] = doc[0].apply(lambda x : re.sub(p, '', str(x)))
    return doc[0]

In [12]:
RegularClear(regex)
doc

0
0      필 땐 장미꽃처럼, 흩날릴 땐 벚꽃처럼, 질 땐 나팔꽃처럼
1           아름다운 그 순간처럼, 어짜피 이것 밖에 난 못해
2                       너를 사랑하는 것 밖엔 못해

In [186]:
import os
%pwd
os.listdir('../') # 파일과 폴더 모두 보여줌
os.listdir('./')

'C:\\Users\\NFSI291\\1A1A\\Book\\script'

['.ipynb_checkpoints', 'data', 'image', 'output', 'script']

['.ipynb_checkpoints',
 '2장 파이썬 프로그래밍.ipynb',
 '3장 데이터 결합 (pandas concate, merge).ipynb',
 '3장 데이터 현황분석.ipynb',
 '3장2절_3절_결측치처리_이상치처리.ipynb',
 '4장 데이터 전처리.ipynb',
 '5장 데이터 시각화.ipynb',
 '6장 특성변수.ipynb',
 '7장1절_2절 머신러닝 알고리즘과 모델.ipynb',
 '7장3절_5절 머신러닝 알고리즘과 모델.ipynb',
 '7장6절_7절 머신러닝 알고리즘과 모델.ipynb',
 '8장1절_2절 머신러닝 응용.ipynb',
 '8장3절 머신러닝 응용.ipynb',
 '8장4절 머신러닝 응용.ipynb',
 'catboost_info',
 'fluent_python_study.ipynb']

In [187]:
for (path, dir, files) in os.walk('../'):
    (dir, files)

(['.ipynb_checkpoints', 'data', 'image', 'output', 'script'], [])

([],
 ['07_ensemble_learning_and_random_forests-checkpoint.ipynb',
  '2-checkpoint.1 연산과 자료형태',
  '2-checkpoint.2_Numpy와_Pandas',
  '2장 파이썬 프로그래밍-checkpoint.ipynb',
  '2장1절_연산과_자료형태-checkpoint.ipynb',
  '2장1절_연산과자료형태-checkpoint.ipynb',
  '2장2절_Numpy_pandas-checkpoint.ipynb',
  '2장2절_Numpy와Pandas-checkpoint.ipynb',
  '2장2절_Numpy와_Pandas-checkpoint.ipynb',
  '2장3절_텍스트처리-checkpoint.ipynb',
  '2장3절_함수와_클래스-checkpoint.ipynb',
  '2장4절_데이터불러오기-checkpoint.ipynb',
  '2장4절_텍스트처리-checkpoint.ipynb',
  '2장5절_데이터불러오기-checkpoint.ipynb',
  '2장_파이썬프로그래밍-checkpoint.ipynb',
  '3장 데이터 현황분석-checkpoint.ipynb',
  '3장1절_데이터분석-checkpoint.ipynb',
  '3장2절_3절_결측치처리_이상치처리-checkpoint.ipynb',
  '3장2절_결측치처리-checkpoint.ipynb',
  '3장4절_파생변수-checkpoint.ipynb',
  '3장5절_5_데이터결합-checkpoint.ipynb',
  '3장5절_데이터전처리방법-checkpoint.ipynb',
  '3장_데이터전처리-checkpoint.ipynb',
  '4장 데이터 전처리-checkpoint.ipynb',
  '4장1절_matplotlib와seaborn시각화-checkpoint.ipynb',
  '4장2절_주성분석과시각화-checkpoint.ipynb',
  '4장3절_지도시각화-checkpoint.ipynb',
  '5장 데이터 

([],
 ['2015년_자전거사고다발지.csv',
  '2016년_자전거사고다발지.csv',
  '2017년_자전거사고다발지.csv',
  '3장자료.pkl',
  '4장3절자료.pkl',
  '4장자료.pkl',
  '4장자료_01.pkl',
  '4장자료_02.pkl',
  'a.xlsx',
  'chicago.pkl',
  'fashion-mnist_test.csv',
  'fashion-mnist_train.csv',
  'food-inspections.csv',
  'food-inspections.pkl',
  'housing.csv',
  'MCR2019.pkl',
  'MCR2019.xlsx',
  'skorea-provinces-2018-geo.json',
  'X.pkl',
  'y.pkl'])

([], [])

([],
 ['correlation_matrix.png',
  'dt.joblib',
  'feature.pkl',
  'feature.xlsx',
  'Feature_importance.png',
  'gnb.joblib',
  'Gradient Boosting.joblib',
  'knn.joblib',
  'lgr.joblib',
  'positive_percent.png',
  'Random Forest.joblib',
  'smote_Decisiontree.joblib',
  'smote_Extra Trees.joblib',
  'smote_GNB.joblib',
  'smote_Gradient Boosting.joblib',
  'smote_KNN.joblib',
  'smote_LGR.joblib',
  'smote_Random Forest.joblib',
  'smote_Ridge.joblib',
  'smote_SVC.joblib',
  'svc.joblib',
  '강원도.html',
  '경기도.html',
  '경상남도.html',
  '경상북도.html',
  '광주광역시.html',
  '대구광역시.html',
  '대전광역시.html',
  '부산광역시.html',
  '서울특별시.html',
  '시도.html',
  '울산광역시.html',
  '인천광역시.html',
  '전국시도.html',
  '전라남도.html',
  '전라북도.html',
  '제주특별자치도.html',
  '충청남도.html',
  '충청북도.html'])

(['.ipynb_checkpoints', 'catboost_info'],
 ['2장 파이썬 프로그래밍.ipynb',
  '3장 데이터 결합 (pandas concate, merge).ipynb',
  '3장 데이터 현황분석.ipynb',
  '3장2절_3절_결측치처리_이상치처리.ipynb',
  '4장 데이터 전처리.ipynb',
  '5장 데이터 시각화.ipynb',
  '6장 특성변수.ipynb',
  '7장1절_2절 머신러닝 알고리즘과 모델.ipynb',
  '7장3절_5절 머신러닝 알고리즘과 모델.ipynb',
  '7장6절_7절 머신러닝 알고리즘과 모델.ipynb',
  '8장1절_2절 머신러닝 응용.ipynb',
  '8장3절 머신러닝 응용.ipynb',
  '8장4절 머신러닝 응용.ipynb',
  'fluent_python_study.ipynb'])

([],
 ['2장 파이썬 프로그래밍-checkpoint.ipynb',
  '3장 데이터 결합 (pandas concate, merge)-checkpoint.ipynb',
  '3장 데이터 현황분석-checkpoint.ipynb',
  '3장2절_3절_결측치처리_이상치처리-checkpoint.ipynb',
  '4장 데이터 전처리-checkpoint.ipynb',
  '5장 데이터 시각화-checkpoint.ipynb',
  '6장 특성변수-checkpoint.ipynb',
  '7장1절_2절 머신러닝 알고리즘과 모델-checkpoint.ipynb',
  '7장3절_5절 머신러닝 알고리즘과 모델-checkpoint.ipynb',
  '7장6절_7절 머신러닝 알고리즘과 모델-checkpoint.ipynb',
  '8장1절_2절 머신러닝 응용-checkpoint.ipynb',
  '8장3절 머신러닝 응용-checkpoint.ipynb',
  '8장4절 머신러닝 응용-checkpoint.ipynb',
  'Chapter_8_1-checkpoint.ipynb',
  'Chapter_8_2-checkpoint.ipynb',
  'Chapter_8_4-checkpoint.ipynb',
  'fluent_python_study-checkpoint.ipynb',
  'Untitled1-checkpoint.ipynb'])

(['fold_0_learn',
  'fold_0_test',
  'fold_1_learn',
  'fold_1_test',
  'fold_2_learn',
  'fold_2_test',
  'fold_3_learn',
  'fold_3_test',
  'learn',
  'test',
  'tmp'],
 ['catboost_training.json',
  'fold_0_learn_error.tsv',
  'fold_0_test_error.tsv',
  'fold_0_time_left.tsv',
  'learn_error.tsv',
  'test_error.tsv',
  'time_left.tsv'])

([], ['events.out.tfevents'])

([], ['events.out.tfevents'])

([], ['events.out.tfevents'])

([], ['events.out.tfevents'])

([], ['events.out.tfevents'])

([], ['events.out.tfevents'])

([], ['events.out.tfevents'])

([], ['events.out.tfevents'])

([], ['events.out.tfevents'])

([], ['events.out.tfevents'])

([], [])

In [188]:
os.makedirs('../data', exist_ok=True)
os.makedirs('../output', exist_ok=True)
os.makedirs('../image', exist_ok=True)

In [189]:
for (path, dir, files) in os.walk('../'):
    (dir, files)

(['.ipynb_checkpoints', 'data', 'image', 'output', 'script'], [])

([],
 ['07_ensemble_learning_and_random_forests-checkpoint.ipynb',
  '2-checkpoint.1 연산과 자료형태',
  '2-checkpoint.2_Numpy와_Pandas',
  '2장 파이썬 프로그래밍-checkpoint.ipynb',
  '2장1절_연산과_자료형태-checkpoint.ipynb',
  '2장1절_연산과자료형태-checkpoint.ipynb',
  '2장2절_Numpy_pandas-checkpoint.ipynb',
  '2장2절_Numpy와Pandas-checkpoint.ipynb',
  '2장2절_Numpy와_Pandas-checkpoint.ipynb',
  '2장3절_텍스트처리-checkpoint.ipynb',
  '2장3절_함수와_클래스-checkpoint.ipynb',
  '2장4절_데이터불러오기-checkpoint.ipynb',
  '2장4절_텍스트처리-checkpoint.ipynb',
  '2장5절_데이터불러오기-checkpoint.ipynb',
  '2장_파이썬프로그래밍-checkpoint.ipynb',
  '3장 데이터 현황분석-checkpoint.ipynb',
  '3장1절_데이터분석-checkpoint.ipynb',
  '3장2절_3절_결측치처리_이상치처리-checkpoint.ipynb',
  '3장2절_결측치처리-checkpoint.ipynb',
  '3장4절_파생변수-checkpoint.ipynb',
  '3장5절_5_데이터결합-checkpoint.ipynb',
  '3장5절_데이터전처리방법-checkpoint.ipynb',
  '3장_데이터전처리-checkpoint.ipynb',
  '4장 데이터 전처리-checkpoint.ipynb',
  '4장1절_matplotlib와seaborn시각화-checkpoint.ipynb',
  '4장2절_주성분석과시각화-checkpoint.ipynb',
  '4장3절_지도시각화-checkpoint.ipynb',
  '5장 데이터 

([],
 ['2015년_자전거사고다발지.csv',
  '2016년_자전거사고다발지.csv',
  '2017년_자전거사고다발지.csv',
  '3장자료.pkl',
  '4장3절자료.pkl',
  '4장자료.pkl',
  '4장자료_01.pkl',
  '4장자료_02.pkl',
  'a.xlsx',
  'chicago.pkl',
  'fashion-mnist_test.csv',
  'fashion-mnist_train.csv',
  'food-inspections.csv',
  'food-inspections.pkl',
  'housing.csv',
  'MCR2019.pkl',
  'MCR2019.xlsx',
  'skorea-provinces-2018-geo.json',
  'X.pkl',
  'y.pkl'])

([], [])

([],
 ['correlation_matrix.png',
  'dt.joblib',
  'feature.pkl',
  'feature.xlsx',
  'Feature_importance.png',
  'gnb.joblib',
  'Gradient Boosting.joblib',
  'knn.joblib',
  'lgr.joblib',
  'positive_percent.png',
  'Random Forest.joblib',
  'smote_Decisiontree.joblib',
  'smote_Extra Trees.joblib',
  'smote_GNB.joblib',
  'smote_Gradient Boosting.joblib',
  'smote_KNN.joblib',
  'smote_LGR.joblib',
  'smote_Random Forest.joblib',
  'smote_Ridge.joblib',
  'smote_SVC.joblib',
  'svc.joblib',
  '강원도.html',
  '경기도.html',
  '경상남도.html',
  '경상북도.html',
  '광주광역시.html',
  '대구광역시.html',
  '대전광역시.html',
  '부산광역시.html',
  '서울특별시.html',
  '시도.html',
  '울산광역시.html',
  '인천광역시.html',
  '전국시도.html',
  '전라남도.html',
  '전라북도.html',
  '제주특별자치도.html',
  '충청남도.html',
  '충청북도.html'])

(['.ipynb_checkpoints', 'catboost_info'],
 ['2장 파이썬 프로그래밍.ipynb',
  '3장 데이터 결합 (pandas concate, merge).ipynb',
  '3장 데이터 현황분석.ipynb',
  '3장2절_3절_결측치처리_이상치처리.ipynb',
  '4장 데이터 전처리.ipynb',
  '5장 데이터 시각화.ipynb',
  '6장 특성변수.ipynb',
  '7장1절_2절 머신러닝 알고리즘과 모델.ipynb',
  '7장3절_5절 머신러닝 알고리즘과 모델.ipynb',
  '7장6절_7절 머신러닝 알고리즘과 모델.ipynb',
  '8장1절_2절 머신러닝 응용.ipynb',
  '8장3절 머신러닝 응용.ipynb',
  '8장4절 머신러닝 응용.ipynb',
  'fluent_python_study.ipynb'])

([],
 ['2장 파이썬 프로그래밍-checkpoint.ipynb',
  '3장 데이터 결합 (pandas concate, merge)-checkpoint.ipynb',
  '3장 데이터 현황분석-checkpoint.ipynb',
  '3장2절_3절_결측치처리_이상치처리-checkpoint.ipynb',
  '4장 데이터 전처리-checkpoint.ipynb',
  '5장 데이터 시각화-checkpoint.ipynb',
  '6장 특성변수-checkpoint.ipynb',
  '7장1절_2절 머신러닝 알고리즘과 모델-checkpoint.ipynb',
  '7장3절_5절 머신러닝 알고리즘과 모델-checkpoint.ipynb',
  '7장6절_7절 머신러닝 알고리즘과 모델-checkpoint.ipynb',
  '8장1절_2절 머신러닝 응용-checkpoint.ipynb',
  '8장3절 머신러닝 응용-checkpoint.ipynb',
  '8장4절 머신러닝 응용-checkpoint.ipynb',
  'Chapter_8_1-checkpoint.ipynb',
  'Chapter_8_2-checkpoint.ipynb',
  'Chapter_8_4-checkpoint.ipynb',
  'fluent_python_study-checkpoint.ipynb',
  'Untitled1-checkpoint.ipynb'])

(['fold_0_learn',
  'fold_0_test',
  'fold_1_learn',
  'fold_1_test',
  'fold_2_learn',
  'fold_2_test',
  'fold_3_learn',
  'fold_3_test',
  'learn',
  'test',
  'tmp'],
 ['catboost_training.json',
  'fold_0_learn_error.tsv',
  'fold_0_test_error.tsv',
  'fold_0_time_left.tsv',
  'learn_error.tsv',
  'test_error.tsv',
  'time_left.tsv'])

([], ['events.out.tfevents'])

([], ['events.out.tfevents'])

([], ['events.out.tfevents'])

([], ['events.out.tfevents'])

([], ['events.out.tfevents'])

([], ['events.out.tfevents'])

([], ['events.out.tfevents'])

([], ['events.out.tfevents'])

([], ['events.out.tfevents'])

([], ['events.out.tfevents'])

([], [])